# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constratints/RAM_ooc.xdc

# XDC: imports/constratints/main_constraint.XDC

# IP: ip/uart_bmpg_0_1/uart_bmpg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_bmpg_0 || ORIG_REF_NAME==uart_bmpg_0} -quiet] -quiet
