# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.cache/wt} [current_project]
set_property parent.project_path {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{g:/Notes/Computer Organization/Proj/scene/uart_m}} [current_project]
set_property ip_output_repo {g:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files G:/FPGA_CPU/asms/offScene1/prgmip32.coe
add_files G:/FPGA_CPU/asms/offScene1/dmem32.coe
add_files G:/FPGA_CPU/asms/offScene2/prgmip32.coe
read_verilog -library xil_defaultlib {
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/code/RenaiCirculation.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/cpu.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/decode.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/dmemory.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/ex_mem.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/execute.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/forwarding.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/gen_regs.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/hazard.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/id_ex.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/if_id.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/mem_wb.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/pc_gen.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/pre_if.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/programrom.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/segment.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/Downloads/vga_num_switch.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/Downloads/vga_top.v}
  {G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/imports/再也不谈恋爱了/top.v}
}
read_ip -quiet {{g:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/uart_bmpg_0_1/uart_bmpg_0.xci}}

read_ip -quiet {{G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/prgrom_2/prgrom.xci}}
set_property used_in_implementation false [get_files -all {{g:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/prgrom_2/prgrom_ooc.xdc}}]

read_ip -quiet {{G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/RAM/RAM.xci}}
set_property used_in_implementation false [get_files -all {{g:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/RAM/RAM_ooc.xdc}}]

read_ip -quiet {{G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/cpuclk/cpuclk.xci}}
set_property used_in_implementation false [get_files -all {{g:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc}}]
set_property used_in_implementation false [get_files -all {{g:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/cpuclk/cpuclk.xdc}}]
set_property used_in_implementation false [get_files -all {{g:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/constrs_1/imports/constratints/RAM_ooc.xdc}}
set_property used_in_implementation false [get_files {{G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/constrs_1/imports/constratints/RAM_ooc.xdc}}]

read_xdc {{G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/constrs_1/imports/constratints/main_constraint.XDC}}
set_property used_in_implementation false [get_files {{G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.srcs/constrs_1/imports/constratints/main_constraint.XDC}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
