webtalk_init -webtalk_dir G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_coe_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 29 02:16:56 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "26c6156f-64f3-405d-905a-254b0b49e2f4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "794da0e0ab5a40eab35e0f32aa9c6c4d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "173" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10360_KB" -context "xsim\\usage"
webtalk_transmit -clientid 199225282 -regid "" -xml G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_coe_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_coe_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/Notes/Computer Organization/Proj/fin/cpu_4/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_coe_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
