webtalk_init -webtalk_dir C:/Users/Administrator/Documents/WeChat Files/wxid_bd4cwvy8r23l22/FileStorage/File/2023-05/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/prgrom_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 23 16:28:47 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a865d4de-b3dc-4d89-b64a-9b77cffc624c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "794da0e0ab5a40eab35e0f32aa9c6c4d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3792 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "22 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8820_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4005218339 -regid "" -xml C:/Users/Administrator/Documents/WeChat Files/wxid_bd4cwvy8r23l22/FileStorage/File/2023-05/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/prgrom_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Administrator/Documents/WeChat Files/wxid_bd4cwvy8r23l22/FileStorage/File/2023-05/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/prgrom_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Administrator/Documents/WeChat Files/wxid_bd4cwvy8r23l22/FileStorage/File/2023-05/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/prgrom_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
